name: skill_bridge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.7.0
  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0
  video_player: ^2.14.0
  razorpay_flutter: ^1.4.7
  cloud_functions: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/skillbridge_logo.png
    - assets/images/developer.gif

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/images/skillbridge_logo.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/skillbridge_logo.png"

  adaptive_icon_foreground_inset: 31

  min_sdk_android: 21
