// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu6LbooXICYNrNYHbcEbPXfqVUhl1KZWw',
    appId: '1:1089966321176:web:43c137160fb8496dd3dd6d',
    messagingSenderId: '1089966321176',
    projectId: 'skill-bridge-57253',
    authDomain: 'skill-bridge-57253.firebaseapp.com',
    storageBucket: 'skill-bridge-57253.firebasestorage.app',
    measurementId: 'G-GK1KWVXHB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuoMCKBB3cPhGkp76_6gF0urA6nGCwSbs',
    appId: '1:1089966321176:android:e8f87bf932688d0bd3dd6d',
    messagingSenderId: '1089966321176',
    projectId: 'skill-bridge-57253',
    storageBucket: 'skill-bridge-57253.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2O1lacfwId_AF628QaRJpZtWQr88Ekw',
    appId: '1:1089966321176:ios:f6a94a66b28f4503d3dd6d',
    messagingSenderId: '1089966321176',
    projectId: 'skill-bridge-57253',
    storageBucket: 'skill-bridge-57253.firebasestorage.app',
    iosBundleId: 'com.example.skillBridge',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2O1lacfwId_AF628QaRJpZtWQr88Ekw',
    appId: '1:1089966321176:ios:f6a94a66b28f4503d3dd6d',
    messagingSenderId: '1089966321176',
    projectId: 'skill-bridge-57253',
    storageBucket: 'skill-bridge-57253.firebasestorage.app',
    iosBundleId: 'com.example.skillBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu6LbooXICYNrNYHbcEbPXfqVUhl1KZWw',
    appId: '1:1089966321176:web:31501277ba2fef27d3dd6d',
    messagingSenderId: '1089966321176',
    projectId: 'skill-bridge-57253',
    authDomain: 'skill-bridge-57253.firebaseapp.com',
    storageBucket: 'skill-bridge-57253.firebasestorage.app',
    measurementId: 'G-YNEVB7WMSG',
  );
}
