// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqC9KNiR-rX12pUcotO-OSZa_gocdzRAY',
    appId: '1:980367306545:web:911d7553b9aaca984c8a10',
    messagingSenderId: '980367306545',
    projectId: 'skill-bridge-e8366',
    authDomain: 'skill-bridge-e8366.firebaseapp.com',
    storageBucket: 'skill-bridge-e8366.firebasestorage.app',
    measurementId: 'G-GZZXFLXY45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MAAYO97zEuyd6szgUZmUYCbwU-mdno8',
    appId: '1:980367306545:android:b25056de240afa374c8a10',
    messagingSenderId: '980367306545',
    projectId: 'skill-bridge-e8366',
    storageBucket: 'skill-bridge-e8366.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTI_kpMN8II47QpMrLDxFaY-Xh90IqoHk',
    appId: '1:980367306545:ios:6caf8c414a9f467e4c8a10',
    messagingSenderId: '980367306545',
    projectId: 'skill-bridge-e8366',
    storageBucket: 'skill-bridge-e8366.firebasestorage.app',
    iosBundleId: 'com.example.skillBridge',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTI_kpMN8II47QpMrLDxFaY-Xh90IqoHk',
    appId: '1:980367306545:ios:6caf8c414a9f467e4c8a10',
    messagingSenderId: '980367306545',
    projectId: 'skill-bridge-e8366',
    storageBucket: 'skill-bridge-e8366.firebasestorage.app',
    iosBundleId: 'com.example.skillBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqC9KNiR-rX12pUcotO-OSZa_gocdzRAY',
    appId: '1:980367306545:web:a3343dda49e154434c8a10',
    messagingSenderId: '980367306545',
    projectId: 'skill-bridge-e8366',
    authDomain: 'skill-bridge-e8366.firebaseapp.com',
    storageBucket: 'skill-bridge-e8366.firebasestorage.app',
    measurementId: 'G-Z2DVZE8WPD',
  );
}
